FROM bitnami/spark:3.5

# Instala o pacote delta-spark
RUN pip install python-dotenv

# Defina variáveis de ambiente
ENV SPARK_HOME=/opt/bitnami/spark
ENV PATH=$SPARK_HOME/bin:$PATH
ENV DATA_LAKE_DIR=data_lake
ENV SCRIPTS_DIR=scripts

# Exponha as portas necessárias
EXPOSE 8080 7077

# Comando de inicialização
CMD ["spark-class", "org.apache.spark.deploy.master.Master"]